baseURL = "http://www.fastnlp.top/"
languageCode = "en-us"
paginate = 4
theme = "portio"
title = "FastNLP"
# Main Menu
[[menu.main]]
name = "Tutorials"
url = "https://fastnlp.readthedocs.io/zh/latest/user/tutorials.html"
weight = 1
[[menu.main]]
name = "Docs"
url = "https://fastnlp.readthedocs.io/zh/latest/"
weight = 2
[[menu.main]]
name = "Quickstart"
url = "https://fastnlp.readthedocs.io/zh/latest/user/quickstart.html"
weight = 3
[[menu.main]]
name = "API"
url = "https://fastnlp.readthedocs.io/zh/latest/fastNLP.html"
weight = 4
[[menu.main]]
name = "About me"
url = "/about"
weight = 5


# Sitemap Menu
[[menu.sitemap]]
name = "FastNLP"
url = "https://gitee.com/fnlp/dashboard/projects/fastnlp/fastNLP/"
weight = 1

[[menu.sitemap]]
name = "FastHan"
url = "https://gitee.com/fnlp/dashboard/projects/fastnlp/fastHan/"
weight = 2

[[menu.sitemap]]
name = "fitlog"
url = "https://gitee.com/fnlp/dashboard/projects/fastnlp/fitlog/"
weight = 3

[[menu.sitemap]]
name = "FastRE"
url = "https://gitee.com/fnlp/dashboard/projects/fastnlp/fastRE/"
weight = 4

[[menu.sitemap]]
name = "FastSum"
url = "https://gitee.com/fnlp/dashboard/projects/fastnlp/fastSum/"
weight = 5


[params]
blogPageURL = "blog"
contactLink = "https://nlp.fudan.edu.cn/"
copyright = "copyright © FNLP 2020 & this theme from Portio 2020"
footerLogo = "images/fastnlp/logo.png"
logo = "images/fastnlp/logo.png"

[params.address]
address = "上海市 杨浦区 复旦大学 计算机科学技术学院 复旦大学自然语言处理实验室"
email = "xpqiu@fudan.edu.cn"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"


